name: "Build"
on:
  push:
    branches:
      - "main"
permissions:
  contents: "write"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      # - name: Run test script
      #   run: node test.js
      # - name: Install Dependencies
      #   working-directory: src
      #   run: npm ci
      - name: Test
        run: npx --yes @hypermode/modus-cli@0.13.2-alpha.1 --version
        env:
          ACTIONS_STEP_DEBUG: true

          