name: "Build"
on:
  push:
    branches:
      - "main"
permissions:
  contents: "write"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: curl -L https://releases.hypermode.com/modus-all.json
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.23.4
      # - run: go version
      # - run: go version
      #   env:
      #     GOTOOLCHAIN: local
