name: "Build"
on:
  push:
    branches:
      - "main"
permissions:
  contents: "write"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        working-directory: ./mjptest
        run: npm install
      - name: Test
        working-directory: ./mjptest
        run: npx foo
        # run: npx --yes @hypermode/modus-cli@0.13.2-alpha.1 --version
        

          