name: "Build"
on:
  push:
    branches:
      - "main"
permissions:
  contents: "write"
jobs:
  build-as:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        working-directory: ./asapp1
        run: npm install
      - name: Build Modus App
        working-directory: ./asapp1
        run: npx -y -p @hypermode/modus-cli modus build
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "./goapp1/go.sum"
          go-version-file: "./goapp1/go.mod"
      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.34.0"
      - name: Build Modus App
        working-directory: ./goapp1
        run: npx -y -p @hypermode/modus-cli modus build
        

          