name: "Build"
on:
  push:
    branches:
      - "main"
    paths:
      - "*.go"
permissions:
  contents: "write"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - run: go version
      - run: go version
        env:
          GOTOOLCHAIN: local
