name: "Release Stuff"

on:
  push:
    tags:
      - "foo/v*"
permissions:
  contents: "write"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ github.ref_name }}"
      - name: Get Version
        run: echo "SDK_VERSION=$(echo ${{ github.ref_name }} | cut -d'/' -f 2)" >> $GITHUB_ENV
      - name: Create Archive
        run: tar -czvf foo_$SDK_VERSION.tar.gz foo
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: foo_$SDK_VERSION.tar.gz
